name: Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure npm for better reliability
        run: |
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          npm config set fetch-retries 3
          npm config set fetch-timeout 300000

      - name: Install dependencies
        run: |
          # Retry npm ci up to 3 times with exponential backoff
          for i in 1 2 3; do
            echo "Attempt $i: Installing dependencies..."
            if npm ci --legacy-peer-deps; then
              echo "Dependencies installed successfully"
              break
            else
              echo "Attempt $i failed"
              if [ $i -eq 3 ]; then
                echo "All attempts failed, exiting"
                exit 1
              fi
              echo "Waiting $((i * 10)) seconds before retry..."
              sleep $((i * 10))
            fi
          done

      - name: Run type checking
        run: npm run typecheck

      - name: Run tests
        run: npm run test

      - name: Build package
        run: npm run build

      - name: Verify package can be packed
        run: npm pack --dry-run

      - name: Check version consistency
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "Tag version ($TAG_VERSION) does not match package.json version ($PACKAGE_VERSION)"
            exit 1
          fi
          echo "Version check passed: $TAG_VERSION"

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
